#!/usr/local/bin/node

'use strict'

let nunjucks = require('nunjucks'),
       files = ['register.njk'];


nunjucks.configure('../views');

files.forEach(function (f) {
    nunjucks.render(f, {title: 'Register'}, function (err,res) {

        if (err)
            throw(err)

        console.log(res)

    })
})
